quarkus:
  http:
    port: 8081

kafka:
  bootstrap:
    servers: PLAINTEXT://kafka:9092

mp:
  messaging:
    incoming:
      about-requested:
        connector: smallrye-kafka
        topic: about.requested
        value:
          deserializer: com.andrea.events.about.kafka.deserializer.AboutRequestedDeserializer
        value-type: com.andrea.events.about.AboutRequested
    outgoing:
      about-responded:
        connector: smallrye-kafka
        topic: about.responded
        value:
          serializer: com.andrea.events.about.kafka.serializer.AboutRespondedSerializer
        value-type: com.andrea.events.about.AboutResponded